//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_GoTest")
#ifdef RESTRICT_GoTest
#define INCLUDE_ALL_GoTest 0
#else
#define INCLUDE_ALL_GoTest 1
#endif
#undef RESTRICT_GoTest

#if !defined (GoTest_) && (INCLUDE_ALL_GoTest || defined(INCLUDE_GoTest))
#define GoTest_

@class IOSObjectArray;

@interface GoTest : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)heyoWithNSString:(NSString *)url;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

@end

J2OBJC_EMPTY_STATIC_INIT(GoTest)

FOUNDATION_EXPORT void GoTest_init(GoTest *self);

FOUNDATION_EXPORT GoTest *new_GoTest_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT GoTest *create_GoTest_init();

FOUNDATION_EXPORT void GoTest_mainWithNSStringArray_(IOSObjectArray *args);

FOUNDATION_EXPORT void GoTest_heyoWithNSString_(NSString *url);

J2OBJC_TYPE_LITERAL_HEADER(GoTest)

#endif

#pragma pop_macro("INCLUDE_ALL_GoTest")
