//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Okhttp3InternalFramedStreamResetException")
#ifdef RESTRICT_Okhttp3InternalFramedStreamResetException
#define INCLUDE_ALL_Okhttp3InternalFramedStreamResetException 0
#else
#define INCLUDE_ALL_Okhttp3InternalFramedStreamResetException 1
#endif
#undef RESTRICT_Okhttp3InternalFramedStreamResetException

#if !defined (Okhttp3InternalFramedStreamResetException_) && (INCLUDE_ALL_Okhttp3InternalFramedStreamResetException || defined(INCLUDE_Okhttp3InternalFramedStreamResetException))
#define Okhttp3InternalFramedStreamResetException_

#define RESTRICT_JavaIoIOException 1
#define INCLUDE_JavaIoIOException 1
#include "java/io/IOException.h"

@class Okhttp3InternalFramedErrorCode;

@interface Okhttp3InternalFramedStreamResetException : JavaIoIOException {
 @public
  Okhttp3InternalFramedErrorCode *errorCode_;
}

#pragma mark Public

- (instancetype)initWithOkhttp3InternalFramedErrorCode:(Okhttp3InternalFramedErrorCode *)errorCode;

@end

J2OBJC_EMPTY_STATIC_INIT(Okhttp3InternalFramedStreamResetException)

J2OBJC_FIELD_SETTER(Okhttp3InternalFramedStreamResetException, errorCode_, Okhttp3InternalFramedErrorCode *)

FOUNDATION_EXPORT void Okhttp3InternalFramedStreamResetException_initWithOkhttp3InternalFramedErrorCode_(Okhttp3InternalFramedStreamResetException *self, Okhttp3InternalFramedErrorCode *errorCode);

FOUNDATION_EXPORT Okhttp3InternalFramedStreamResetException *new_Okhttp3InternalFramedStreamResetException_initWithOkhttp3InternalFramedErrorCode_(Okhttp3InternalFramedErrorCode *errorCode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalFramedStreamResetException *create_Okhttp3InternalFramedStreamResetException_initWithOkhttp3InternalFramedErrorCode_(Okhttp3InternalFramedErrorCode *errorCode);

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalFramedStreamResetException)

#endif

#pragma pop_macro("INCLUDE_ALL_Okhttp3InternalFramedStreamResetException")
